package com.mycompany.tfg;

import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Álvaro
 */
public class AñadirV extends javax.swing.JFrame {

    /**
     * Creates new form AñadirV
     */
    public AñadirV() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        modelotx = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        matricula = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        matriculatx = new javax.swing.JTextField();
        añotx = new javax.swing.JTextField();
        proptx = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        colortx = new javax.swing.JTextField();
        kmtx = new javax.swing.JTextField();
        itvtx = new javax.swing.JTextField();
        serviciobox = new javax.swing.JComboBox<>();
        borrarbut = new javax.swing.JButton();
        volverbut1 = new javax.swing.JButton();
        enviarbut = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        marcatx = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("   Vehiculos");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Añadir", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 47, 168, 83));
        jPanel1.add(modelotx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 180, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Modelo:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, -1, -1));

        matricula.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        matricula.setForeground(new java.awt.Color(255, 255, 255));
        matricula.setText("Matricula:");
        jPanel1.add(matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 170, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Año:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 60, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Servicio:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 290, -1, -1));
        jPanel1.add(matriculatx, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 170, 180, -1));
        jPanel1.add(añotx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 290, 180, -1));
        jPanel1.add(proptx, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 230, 180, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kilometraje:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Color:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 470, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Caducidad ITV:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 410, -1, -1));
        jPanel1.add(colortx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 470, 180, -1));
        jPanel1.add(kmtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 180, -1));
        jPanel1.add(itvtx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 410, 180, -1));

        serviciobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Revisión general", "Chapa", "Pintura", "Reparación piezas", "Ruedas" }));
        serviciobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicioboxActionPerformed(evt);
            }
        });
        jPanel1.add(serviciobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 290, 180, 40));

        borrarbut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        borrarbut.setText("Borrar");
        borrarbut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        borrarbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarbutActionPerformed(evt);
            }
        });
        jPanel1.add(borrarbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 490, 150, 50));

        volverbut1.setBackground(new java.awt.Color(255, 255, 153));
        volverbut1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        volverbut1.setText("Volver");
        volverbut1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        volverbut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverbut1ActionPerformed(evt);
            }
        });
        jPanel1.add(volverbut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 700, 110, 50));

        enviarbut.setBackground(new java.awt.Color(153, 255, 153));
        enviarbut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        enviarbut.setText("Añadir");
        enviarbut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        enviarbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarbutActionPerformed(evt);
            }
        });
        jPanel1.add(enviarbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 490, 150, 50));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Propietario:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 230, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Marca:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, -1, 30));
        jPanel1.add(marcatx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 170, 180, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("*");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 10, 20));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 51, 51));
        jLabel11.setText("- Utilizar guión en campo ITV (dd-mm-aa)");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 360, 30));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 51, 51));
        jLabel12.setText("-");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 10, 20));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 51, 51));
        jLabel13.setText("*");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 10, 20));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 51, 51));
        jLabel14.setText("* Campo obligatorio");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 730, 240, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1090, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void servicioboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicioboxActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_servicioboxActionPerformed

    private void borrarbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarbutActionPerformed
        // TODO add your handling code here:
        marcatx.setText("");
        modelotx.setText("");
        añotx.setText("");
        kmtx.setText("");
        itvtx.setText("");
        colortx.setText("");
        proptx.setText("");
        matriculatx.setText("");
        serviciobox.setSelectedItem("-");
    }//GEN-LAST:event_borrarbutActionPerformed

    private void volverbut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverbut1ActionPerformed
        // TODO add your handling code here:
        Vehiculos v = new Vehiculos();
        dispose();
        v.setVisible(true);
        v.setLocationRelativeTo(null);
        
    }//GEN-LAST:event_volverbut1ActionPerformed

    private void enviarbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarbutActionPerformed
       
                try {
                // Obtener los valores de los campos de texto
                String marca = marcatx.getText();
                String modelo = modelotx.getText();
                String año = añotx.getText();
                int kilometraje = Integer.parseInt(kmtx.getText());
                String itv = itvtx.getText();
                String color = colortx.getText();
                String matricula = matriculatx.getText();
                String propietario = proptx.getText();
                String servicio = serviciobox.getSelectedItem().toString();
                
                // Crear un objeto Vehiculo con los valores obtenidos
                Vehiculo vehiculo = new Vehiculo();
                vehiculo.setMarcaV(marca);
                vehiculo.setModeloV(modelo);
                vehiculo.setAñoV(año);
                vehiculo.setKilometrajeV(kilometraje);
                vehiculo.setItvV(itv);
                vehiculo.setColorV(color);
                vehiculo.setMatriculaV(matricula);
                vehiculo.setPropietarioV(propietario);
                vehiculo.setServicioV(servicio);
                
                
                if (matricula.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El campo matricula es obligatorio.", "Error", JOptionPane.ERROR_MESSAGE);
                matriculatx.setText("");
            } else if (propietario.isEmpty()) {
                JOptionPane.showMessageDialog(this, "El campo propietario es obligatorio.", "Error", JOptionPane.ERROR_MESSAGE);
                proptx.setText("");
            } else {
                // Crear un objeto VehiculoDAO y agregar el vehículo a la base de datos
                VehiculoDAO vehiculoDAO = new VehiculoDAO();
                vehiculoDAO.agregarVehiculo(vehiculo);

                marcatx.setText("");
                modelotx.setText("");
                añotx.setText("");
                kmtx.setText("");
                itvtx.setText("");
                colortx.setText("");
                proptx.setText("");
                matriculatx.setText("");
                serviciobox.setSelectedItem("-");
            }
                
                // Mostrar mensaje de éxito
            } catch (NumberFormatException e) {
                // Manejar excepción si no se pueden convertir las cadenas en enteros
                JOptionPane.showMessageDialog(null, "Error: El año y kilometraje deben ser números enteros.", "Error", JOptionPane.ERROR_MESSAGE);
            } catch (Exception e) {
                // Manejar cualquier otra excepción que pueda ocurrir
                JOptionPane.showMessageDialog(null, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
           
    }//GEN-LAST:event_enviarbutActionPerformed

    /**
     * @param marca
     * @param args the command line arguments
     */


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AñadirV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AñadirV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AñadirV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AñadirV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AñadirV().setVisible(true);
                
                ConexionMongo conexion;
                
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField añotx;
    private javax.swing.JButton borrarbut;
    private javax.swing.JTextField colortx;
    private javax.swing.JButton enviarbut;
    private javax.swing.JTextField itvtx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField kmtx;
    private javax.swing.JTextField marcatx;
    private javax.swing.JLabel matricula;
    private javax.swing.JTextField matriculatx;
    private javax.swing.JTextField modelotx;
    private javax.swing.JTextField proptx;
    public javax.swing.JComboBox<String> serviciobox;
    private javax.swing.JButton volverbut1;
    // End of variables declaration//GEN-END:variables
}
