/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tfg;

import java.awt.Dimension;
import java.awt.FontMetrics;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Álvaro
 */
public class BorrarV extends javax.swing.JFrame {

        private VehiculoDAO vehiculoDAO;

    /**
     * Creates new form BorrarV
     */
    public BorrarV() {
        initComponents();
        vehiculoDAO = new VehiculoDAO(); // Inicializar vehiculoDAO aquí

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        matricula = new javax.swing.JLabel();
        borrarmatriculatx = new javax.swing.JTextField();
        borrarproptx = new javax.swing.JTextField();
        borrarbut = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        volverbut2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        buscarbut1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        textofieldoB = new javax.swing.JTextArea();
        limpiarbut = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("   Vehiculos");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Borrar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 47, 168, 83));

        matricula.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        matricula.setForeground(new java.awt.Color(255, 255, 255));
        matricula.setText("Matricula:");
        jPanel1.add(matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));
        jPanel1.add(borrarmatriculatx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 180, -1));
        jPanel1.add(borrarproptx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 180, -1));

        borrarbut.setBackground(new java.awt.Color(255, 51, 51));
        borrarbut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        borrarbut.setText("Borrar");
        borrarbut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        borrarbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarbutActionPerformed(evt);
            }
        });
        jPanel1.add(borrarbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 380, 120, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Propietario:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        volverbut2.setBackground(new java.awt.Color(255, 255, 153));
        volverbut2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        volverbut2.setText("Volver");
        volverbut2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        volverbut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverbut2ActionPerformed(evt);
            }
        });
        jPanel1.add(volverbut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 700, 100, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("Vehiculo :");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 130, -1, -1));

        buscarbut1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buscarbut1.setText("Buscar");
        buscarbut1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        buscarbut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarbut1ActionPerformed(evt);
            }
        });
        jPanel1.add(buscarbut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 120, 40));

        textofieldoB.setEditable(false);
        textofieldoB.setBackground(new java.awt.Color(204, 255, 204));
        textofieldoB.setColumns(20);
        textofieldoB.setFont(new java.awt.Font("Calibri", 3, 22)); // NOI18N
        textofieldoB.setRows(5);
        textofieldoB.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textofieldoB.setMargin(new java.awt.Insets(6, 12, 6, 12));
        jScrollPane3.setViewportView(textofieldoB);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 430, 490));

        limpiarbut.setBackground(new java.awt.Color(255, 207, 139));
        limpiarbut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        limpiarbut.setText("Limpiar");
        limpiarbut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        limpiarbut.setPreferredSize(new java.awt.Dimension(57, 31));
        limpiarbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarbutActionPerformed(evt);
            }
        });
        jPanel1.add(limpiarbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 120, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1050, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void borrarbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarbutActionPerformed
        // TODO add your handling code here:
        String matricula = borrarmatriculatx.getText(); // Obtener la matrícula del JTextField
        String propietario = borrarproptx.getText(); // Obtener el propietario del JTextField

        if (matricula.isEmpty() || propietario.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Por favor, ingrese la matrícula y el propietario para borrar el vehículo.", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Estás seguro de que deseas borrar este vehículo?", "Confirmar Borrado", JOptionPane.YES_NO_OPTION);
        if (confirmacion == JOptionPane.YES_OPTION) {
            vehiculoDAO.borrarVehiculo(matricula, propietario);
            JOptionPane.showMessageDialog(null, "Vehículo borrado exitosamente.", "Borrado Exitoso", JOptionPane.INFORMATION_MESSAGE);
            // Puedes limpiar los campos o actualizar la interfaz aquí si es necesario
        }
        textofieldoB.setText("");
    }//GEN-LAST:event_borrarbutActionPerformed

    private void volverbut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverbut2ActionPerformed
        // TODO add your handling code here:
        Vehiculos v = new Vehiculos();
        dispose();
        v.setVisible(true);
        v.setLocationRelativeTo(null);
    }//GEN-LAST:event_volverbut2ActionPerformed

    private void buscarbut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarbut1ActionPerformed
        // TODO add your handling code here:
    String matricula = borrarmatriculatx.getText();
    String propietario = borrarproptx.getText();

    // Llamar al método buscarVehiculo del VehiculoDAO
    VehiculoDAO vehiculoDAO = new VehiculoDAO();
    List<Vehiculo> vehiculosEncontrados = vehiculoDAO.buscarVehiculo(matricula, propietario);

    // Mostrar el primer vehículo encontrado en el TextField txtResultado
    if (!vehiculosEncontrados.isEmpty()) {
        Vehiculo vehiculoEncontrado = vehiculosEncontrados.get(0);

   
    
       String infoVehiculo = "Marca: " + vehiculoEncontrado.getMarcaV() + "\n"  +
                      "Modelo: " + vehiculoEncontrado.getModeloV() + "\n"  +
                      "Año: " + vehiculoEncontrado.getAñoV() + "\n" +
                      "Kilometraje: " + vehiculoEncontrado.getKilometrajeV() + " km"+ "\n" +
                      "Fecha caducidad ITV: " + vehiculoEncontrado.getItvV() + "\n"  +
                      "Color: " + vehiculoEncontrado.getColorV() + "\n" +
                      "Matrícula: " + vehiculoEncontrado.getMatriculaV() + "\n"+
                      "Propietario: " + vehiculoEncontrado.getPropietarioV() + "\n"+
                      "Servicio: " + vehiculoEncontrado.getServicioV();

                // Ajustar el tamaño del TextField
               FontMetrics metrics = textofieldoB.getFontMetrics(textofieldoB.getFont());
                int width = metrics.stringWidth(infoVehiculo);
                int height = metrics.getHeight();
                textofieldoB.setPreferredSize(new Dimension(width, height));

        textofieldoB.setText(infoVehiculo);
    } else {
        textofieldoB.setText("Vehículo no encontrado.");
    }

    // Limpiar los campos después de la búsqueda (opcional)
    
    }//GEN-LAST:event_buscarbut1ActionPerformed

    private void limpiarbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarbutActionPerformed
        // TODO add your handling code here:
        borrarmatriculatx.setText("");
        borrarproptx.setText("");
    }//GEN-LAST:event_limpiarbutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BorrarV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BorrarV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BorrarV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BorrarV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BorrarV().setVisible(true);
            }
        });
    
}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton borrarbut;
    private javax.swing.JTextField borrarmatriculatx;
    private javax.swing.JTextField borrarproptx;
    private javax.swing.JButton buscarbut1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton limpiarbut;
    private javax.swing.JLabel matricula;
    private javax.swing.JTextArea textofieldoB;
    private javax.swing.JButton volverbut2;
    // End of variables declaration//GEN-END:variables

}