/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tfg;

import java.awt.Dimension;
import java.awt.FontMetrics;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Álvaro
 */
public class BuscarV extends javax.swing.JFrame {

    /**
     * Creates new form BuscarV
     */
    public BuscarV() {
        initComponents();
        clienterojoLabel.setVisible(false);        
        puntorojolabel1.setVisible(false);
        clienteverdeLabel.setVisible(false);
        puntoverdeLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enviarbut = new javax.swing.JButton();
        borrarbut = new javax.swing.JButton();
        serviciobox = new javax.swing.JComboBox<>();
        añotx = new javax.swing.JTextField();
        kmtx = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        colortx = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        itvtx = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        modelotx = new javax.swing.JTextField();
        marcatx1 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        matricula = new javax.swing.JLabel();
        matriculatx = new javax.swing.JTextField();
        proptx = new javax.swing.JTextField();
        borrbutB = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        volverbut2 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        buscarbut1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        textofieldo = new javax.swing.JTextArea();
        puntoverdeLabel = new javax.swing.JLabel();
        clienteverdeLabel = new javax.swing.JLabel();
        puntorojolabel1 = new javax.swing.JLabel();
        clienterojoLabel = new javax.swing.JLabel();

        enviarbut.setText("Enviar");
        enviarbut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        enviarbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarbutActionPerformed(evt);
            }
        });

        borrarbut.setText("Borrar");
        borrarbut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        borrarbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarbutActionPerformed(evt);
            }
        });

        serviciobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Revisión general", "Chapa", "Pintura", "Reparación piezas", "Ruedas" }));
        serviciobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicioboxActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kilometraje:");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Caducidad ITV:");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Servicio:");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Color:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Año:");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Modelo:");

        jLabel10.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Marca:");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("   Vehiculos");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 47, 168, 83));

        matricula.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        matricula.setForeground(new java.awt.Color(255, 255, 255));
        matricula.setText("Matricula:");
        jPanel1.add(matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));
        jPanel1.add(matriculatx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 180, -1));
        jPanel1.add(proptx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 180, -1));

        borrbutB.setBackground(new java.awt.Color(255, 207, 139));
        borrbutB.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        borrbutB.setText("Limpiar");
        borrbutB.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        borrbutB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrbutBActionPerformed(evt);
            }
        });
        jPanel1.add(borrbutB, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 240, 120, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Propietario:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        volverbut2.setBackground(new java.awt.Color(255, 255, 153));
        volverbut2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        volverbut2.setText("Volver");
        volverbut2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        volverbut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverbut2ActionPerformed(evt);
            }
        });
        jPanel1.add(volverbut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 700, 110, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("Vehiculo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 340, -1, 40));

        buscarbut1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buscarbut1.setText("Buscar");
        buscarbut1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        buscarbut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarbut1ActionPerformed(evt);
            }
        });
        jPanel1.add(buscarbut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 120, 40));

        textofieldo.setEditable(false);
        textofieldo.setBackground(new java.awt.Color(204, 255, 204));
        textofieldo.setColumns(20);
        textofieldo.setFont(new java.awt.Font("Calibri", 3, 22)); // NOI18N
        textofieldo.setRows(5);
        textofieldo.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textofieldo.setMargin(new java.awt.Insets(6, 12, 6, 12));
        jScrollPane3.setViewportView(textofieldo);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 810, 320));

        puntoverdeLabel.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        puntoverdeLabel.setForeground(new java.awt.Color(51, 255, 0));
        puntoverdeLabel.setText("●");
        jPanel1.add(puntoverdeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 40, -1, -1));

        clienteverdeLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        clienteverdeLabel.setForeground(new java.awt.Color(51, 255, 51));
        clienteverdeLabel.setText("Cliente");
        jPanel1.add(clienteverdeLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 70, -1, -1));

        puntorojolabel1.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        puntorojolabel1.setForeground(new java.awt.Color(255, 0, 0));
        puntorojolabel1.setText("●");
        jPanel1.add(puntorojolabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 80, -1, -1));

        clienterojoLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        clienterojoLabel.setForeground(new java.awt.Color(255, 0, 0));
        clienterojoLabel.setText("Cliente");
        jPanel1.add(clienterojoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 110, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1092, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void servicioboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicioboxActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_servicioboxActionPerformed

    private void borrarbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarbutActionPerformed
        //ODO add your handling code here:
     
    }//GEN-LAST:event_borrarbutActionPerformed

    private void borrbutBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrbutBActionPerformed
        matriculatx.setText("");
        proptx.setText("");
        clienterojoLabel.setVisible(false);        
        puntorojolabel1.setVisible(false);
        clienteverdeLabel.setVisible(false);
        puntoverdeLabel.setVisible(false);
                                             
        
    }//GEN-LAST:event_borrbutBActionPerformed

    private void enviarbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarbutActionPerformed
        // TODO add your handling code here:
      
    }//GEN-LAST:event_enviarbutActionPerformed

    private void volverbut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverbut2ActionPerformed
        // TODO add your handling code here:
        Vehiculos v = new Vehiculos();
        dispose();
        v.setVisible(true);
        v.setLocationRelativeTo(null);
    }//GEN-LAST:event_volverbut2ActionPerformed

    private void buscarbut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarbut1ActionPerformed
        // TODO add your handling code here:
    String matricula = matriculatx.getText();
    String propietario = proptx.getText();

    // Llamar al método buscarVehiculo del VehiculoDAO
    VehiculoDAO vehiculoDAO = new VehiculoDAO();
    List<Vehiculo> vehiculosEncontrados = vehiculoDAO.buscarVehiculo(matricula, propietario);

    // Mostrar el primer vehículo encontrado en el TextField txtResultado
    if (!vehiculosEncontrados.isEmpty()) {
        if(clienterojoLabel.isVisible()&& puntorojolabel1.isVisible()){
                clienterojoLabel.setVisible(false);        
                puntorojolabel1.setVisible(false);
            }
            clienteverdeLabel.setVisible(true);
            puntoverdeLabel.setVisible(true);
            
        Vehiculo vehiculoEncontrado = vehiculosEncontrados.get(0);
    
       String infoVehiculo = "Marca: " + vehiculoEncontrado.getMarcaV() + "\n"  +
                      "Modelo: " + vehiculoEncontrado.getModeloV() + "\n"  +
                      "Año: " + vehiculoEncontrado.getAñoV() + "\n" +
                      "Kilometraje: " + vehiculoEncontrado.getKilometrajeV() + " km"+ "\n" +
                      "Fecha caducidad ITV: " + vehiculoEncontrado.getItvV() + "\n"  +
                      "Color: " + vehiculoEncontrado.getColorV() + "\n" +
                      "Matrícula: " + vehiculoEncontrado.getMatriculaV() + "\n"+
                      "Propietario: " + vehiculoEncontrado.getPropietarioV() + "\n"+
                      "Servicio: " + vehiculoEncontrado.getServicioV();

                // Ajustar el tamaño del TextField
                FontMetrics metrics = textofieldo.getFontMetrics(textofieldo.getFont());
                int width = metrics.stringWidth(infoVehiculo);
                int height = metrics.getHeight();
                textofieldo.setPreferredSize(new Dimension(width, height));

        textofieldo.setText(infoVehiculo);
    } else {
            textofieldo.setText("Vehículo no encontrado.");
            if(clienteverdeLabel.isVisible()&& puntoverdeLabel.isVisible()){
                clienteverdeLabel.setVisible(false);        
                puntoverdeLabel.setVisible(false);
            }
     clienterojoLabel.setVisible(true);        
     puntorojolabel1.setVisible(true);
  }
    matriculatx.setText("");
    proptx.setText("");
    }//GEN-LAST:event_buscarbut1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField añotx;
    private javax.swing.JButton borrarbut;
    private javax.swing.JButton borrbutB;
    private javax.swing.JButton buscarbut1;
    private javax.swing.JLabel clienterojoLabel;
    private javax.swing.JLabel clienteverdeLabel;
    private javax.swing.JTextField colortx;
    private javax.swing.JButton enviarbut;
    private javax.swing.JTextField itvtx;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField kmtx;
    private javax.swing.JTextField marcatx1;
    private javax.swing.JLabel matricula;
    private javax.swing.JTextField matriculatx;
    private javax.swing.JTextField modelotx;
    private javax.swing.JTextField proptx;
    private javax.swing.JLabel puntorojolabel1;
    private javax.swing.JLabel puntoverdeLabel;
    public javax.swing.JComboBox<String> serviciobox;
    private javax.swing.JTextArea textofieldo;
    private javax.swing.JButton volverbut2;
    // End of variables declaration//GEN-END:variables
}
