/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tfg;

import java.awt.Dimension;
import java.awt.FontMetrics;
import java.util.List;

/**
 *
 * @author Álvaro
 */
public class BuscarC extends javax.swing.JFrame {

    /**
     * Creates new form BuscarC
     */
    public BuscarC() {
        initComponents();
        clienterojoLabel.setVisible(false);        
        puntorojolabel1.setVisible(false);
        clienteverdeLabel.setVisible(false);
        puntoverdeLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dnitxbuscar = new javax.swing.JTextField();
        buscarbut = new javax.swing.JButton();
        limpiarbut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoAreo = new javax.swing.JTextArea();
        volverbut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        puntoverdeLabel = new javax.swing.JLabel();
        clienteverdeLabel = new javax.swing.JLabel();
        clienterojoLabel = new javax.swing.JLabel();
        puntorojolabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1109, 779));
        setPreferredSize(new java.awt.Dimension(1109, 779));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setPreferredSize(new java.awt.Dimension(1109, 779));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("       Clientes");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Buscar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DNI / NIE:");

        buscarbut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buscarbut.setText("Buscar");
        buscarbut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        buscarbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarbutActionPerformed(evt);
            }
        });

        limpiarbut.setBackground(new java.awt.Color(255, 207, 139));
        limpiarbut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        limpiarbut.setText("Limpiar");
        limpiarbut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        limpiarbut.setPreferredSize(new java.awt.Dimension(57, 31));
        limpiarbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarbutActionPerformed(evt);
            }
        });

        textoAreo.setEditable(false);
        textoAreo.setBackground(new java.awt.Color(204, 204, 255));
        textoAreo.setColumns(20);
        textoAreo.setFont(new java.awt.Font("Calibri", 3, 22)); // NOI18N
        textoAreo.setRows(5);
        textoAreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        textoAreo.setMargin(new java.awt.Insets(8, 8, 8, 8));
        jScrollPane1.setViewportView(textoAreo);

        volverbut.setBackground(new java.awt.Color(255, 255, 153));
        volverbut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        volverbut.setText("Volver");
        volverbut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        volverbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverbutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cliente :");

        puntoverdeLabel.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        puntoverdeLabel.setForeground(new java.awt.Color(51, 255, 0));
        puntoverdeLabel.setText("●");

        clienteverdeLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        clienteverdeLabel.setForeground(new java.awt.Color(51, 255, 51));
        clienteverdeLabel.setText("Cliente");

        clienterojoLabel.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        clienterojoLabel.setForeground(new java.awt.Color(255, 0, 0));
        clienterojoLabel.setText("Cliente");

        puntorojolabel1.setFont(new java.awt.Font("Segoe UI", 1, 60)); // NOI18N
        puntorojolabel1.setForeground(new java.awt.Color(255, 0, 0));
        puntorojolabel1.setText("●");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(volverbut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGap(98, 98, 98)
                                    .addComponent(jLabel6)
                                    .addGap(18, 18, 18))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addContainerGap()
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(8, 8, 8)))
                            .addComponent(dnitxbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(135, 135, 135)
                            .addComponent(buscarbut, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(limpiarbut, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(86, 86, 86))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(clienteverdeLabel)
                                .addComponent(clienterojoLabel))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(puntoverdeLabel)
                                .addComponent(puntorojolabel1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(161, 161, 161)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 714, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))))
                .addContainerGap(176, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(clienteverdeLabel))
                            .addComponent(puntoverdeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(clienterojoLabel))
                    .addComponent(puntorojolabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(dnitxbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(buscarbut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(limpiarbut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 63, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(volverbut, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1089, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 785, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarbutActionPerformed
        // TODO add your handling code here:
        String dni = dnitxbuscar.getText();
        ClientesDAO clientesDAO = new ClientesDAO();
        List<Cliente> clientesEncontrados = clientesDAO.buscarCliente(dni);

        if (!clientesEncontrados.isEmpty()) {
            if(clienterojoLabel.isVisible()&& puntorojolabel1.isVisible()){
                clienterojoLabel.setVisible(false);        
                puntorojolabel1.setVisible(false);
            }
            clienteverdeLabel.setVisible(true);
            puntoverdeLabel.setVisible(true);
            Cliente cEncontrado = clientesEncontrados.get(0);

            String infoCliente = "Nombre: " + cEncontrado.getNombreC()+ "\n"  +
            "Primer apellido: " + cEncontrado.getApellido1C()+ "\n"  +
            "Segundo apellido: " + cEncontrado.getApellido2C()+ "\n" +
            "Teléfono: " + cEncontrado.getTelefonoC()+ "\n" +
            "DNI / NIF: " + cEncontrado.getDniC()+ "\n"  +
            "Dirección: " + cEncontrado.getDireccionC()+ "\n" +
            "Correo electrónico: " + cEncontrado.getCorreoC()+ "\n"+
            "Coches en propiedad: " + cEncontrado.getCochesPropC()+ "\n"+
            "¿Cómo nos conociste?: " + cEncontrado.getConocisteC();

            // Ajustar el tamaño del TextField
            FontMetrics metrics = textoAreo.getFontMetrics(textoAreo.getFont());
            int width = metrics.stringWidth(infoCliente);
            int height = metrics.getHeight();
            textoAreo.setPreferredSize(new Dimension(width, height));

            textoAreo.setText(infoCliente);
        } else {
            textoAreo.setText("Cliente no encontrado.");
            if(clienteverdeLabel.isVisible()&& puntoverdeLabel.isVisible()){
                clienteverdeLabel.setVisible(false);        
                puntoverdeLabel.setVisible(false);
            }
            clienterojoLabel.setVisible(true);        
            puntorojolabel1.setVisible(true);
        }
    }//GEN-LAST:event_buscarbutActionPerformed

    private void limpiarbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarbutActionPerformed
        // TODO add your handling code here:
        dnitxbuscar.setText("");
        clienterojoLabel.setVisible(false);        
        puntorojolabel1.setVisible(false);
        clienteverdeLabel.setVisible(false);
        puntoverdeLabel.setVisible(false);
    }//GEN-LAST:event_limpiarbutActionPerformed

    private void volverbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverbutActionPerformed
        // TODO add your handling code here:
        Clientes c = new Clientes();
        dispose();
        c.setVisible(true);
        c.setLocationRelativeTo(null);
    }//GEN-LAST:event_volverbutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BuscarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BuscarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BuscarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BuscarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BuscarC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarbut;
    private javax.swing.JLabel clienterojoLabel;
    private javax.swing.JLabel clienteverdeLabel;
    private javax.swing.JTextField dnitxbuscar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiarbut;
    private javax.swing.JLabel puntorojolabel1;
    private javax.swing.JLabel puntoverdeLabel;
    private javax.swing.JTextArea textoAreo;
    private javax.swing.JButton volverbut;
    // End of variables declaration//GEN-END:variables
}
