/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tfg;

/**
 *
 * @author Álvaro
 */
public class Clientes extends javax.swing.JFrame {

    /**
     * Creates new form Clientes
     */
    public Clientes() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        volvbut = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        borrarclientebut = new javax.swing.JButton();
        modificarclientebut = new javax.swing.JButton();
        buscarclientebut = new javax.swing.JButton();
        añadirclientebut = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        volvbut.setBackground(new java.awt.Color(255, 255, 153));
        volvbut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        volvbut.setText("Volver");
        volvbut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        volvbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volvbutActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 3, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Clientes");

        borrarclientebut.setBackground(new java.awt.Color(51, 51, 51));
        borrarclientebut.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        borrarclientebut.setForeground(new java.awt.Color(255, 255, 255));
        borrarclientebut.setText("Borrar cliente");
        borrarclientebut.setMaximumSize(new java.awt.Dimension(224, 42));
        borrarclientebut.setMinimumSize(new java.awt.Dimension(224, 42));
        borrarclientebut.setPreferredSize(new java.awt.Dimension(224, 42));
        borrarclientebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarclientebutActionPerformed(evt);
            }
        });

        modificarclientebut.setBackground(new java.awt.Color(51, 51, 51));
        modificarclientebut.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        modificarclientebut.setForeground(new java.awt.Color(255, 255, 255));
        modificarclientebut.setText("Modificar cliente");
        modificarclientebut.setMaximumSize(new java.awt.Dimension(224, 42));
        modificarclientebut.setMinimumSize(new java.awt.Dimension(224, 42));
        modificarclientebut.setPreferredSize(new java.awt.Dimension(224, 42));
        modificarclientebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarclientebutActionPerformed(evt);
            }
        });

        buscarclientebut.setBackground(new java.awt.Color(51, 51, 51));
        buscarclientebut.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        buscarclientebut.setForeground(new java.awt.Color(255, 255, 255));
        buscarclientebut.setText("Buscar cliente");
        buscarclientebut.setMaximumSize(new java.awt.Dimension(224, 42));
        buscarclientebut.setMinimumSize(new java.awt.Dimension(224, 42));
        buscarclientebut.setPreferredSize(new java.awt.Dimension(224, 42));
        buscarclientebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarclientebutActionPerformed(evt);
            }
        });

        añadirclientebut.setBackground(new java.awt.Color(51, 51, 51));
        añadirclientebut.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        añadirclientebut.setForeground(new java.awt.Color(255, 255, 255));
        añadirclientebut.setText("Añadir cliente");
        añadirclientebut.setMaximumSize(new java.awt.Dimension(224, 42));
        añadirclientebut.setMinimumSize(new java.awt.Dimension(224, 42));
        añadirclientebut.setPreferredSize(new java.awt.Dimension(224, 42));
        añadirclientebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                añadirclientebutActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 28)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(204, 255, 255));
        jLabel2.setText("¿Qué gestión desea realizar?");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(234, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(volvbut, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(borrarclientebut, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(añadirclientebut, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(95, 95, 95)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(modificarclientebut, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarclientebut, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(253, 253, 253))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(337, 337, 337)
                        .addComponent(jLabel2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(volvbut, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(añadirclientebut, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modificarclientebut, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(borrarclientebut, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(buscarclientebut, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(242, 242, 242))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volvbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volvbutActionPerformed
        // TODO add your handling code here:
        Inicio ini = new Inicio();
        dispose();
        ini.setVisible(true);
        ini.setLocationRelativeTo(null);
    }//GEN-LAST:event_volvbutActionPerformed

    private void añadirclientebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añadirclientebutActionPerformed
        // TODO add your handling code here:
        AñadirC c = new AñadirC();
        dispose();
        c.setVisible(true);
        c.setLocationRelativeTo(null);
    }//GEN-LAST:event_añadirclientebutActionPerformed

    private void borrarclientebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarclientebutActionPerformed
        // TODO add your handling code here:
        BorrarC bc = new BorrarC();
        dispose();
        bc.setVisible(true);
        bc.setLocationRelativeTo(null);
    }//GEN-LAST:event_borrarclientebutActionPerformed

    private void buscarclientebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarclientebutActionPerformed
        // TODO add your handling code here:
        BuscarC bsc = new BuscarC();
        dispose();
        bsc.setVisible(true);
        bsc.setLocationRelativeTo(null);
    }//GEN-LAST:event_buscarclientebutActionPerformed

    private void modificarclientebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarclientebutActionPerformed
        // TODO add your handling code here:
        ModificarC mc = new ModificarC();
        dispose();
        mc.setVisible(true);
        mc.setLocationRelativeTo(null);
    }//GEN-LAST:event_modificarclientebutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Clientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Clientes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton añadirclientebut;
    private javax.swing.JButton borrarclientebut;
    private javax.swing.JButton buscarclientebut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton modificarclientebut;
    private javax.swing.JButton volvbut;
    // End of variables declaration//GEN-END:variables
}
