/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tfg;

import java.awt.Dimension;
import java.awt.FontMetrics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author Álvaro
 */
public class ModificarV extends javax.swing.JFrame {

    /**
     * Creates new form ModificarV
     */
        private Vehiculo vehiculo;
        private final VehiculoDAO vehiculoDAO;

    public ModificarV() {
        initComponents();
        vehiculoDAO = new VehiculoDAO(); // Inicializar vehiculoDAO aquí

        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        matricula = new javax.swing.JLabel();
        matriculatx = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        volverbut2 = new javax.swing.JButton();
        mtfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        limpiarbut = new javax.swing.JButton();
        serviciobox = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        textofieldoM = new javax.swing.JTextArea();
        buscarbut1 = new javax.swing.JButton();
        modelobut = new javax.swing.JButton();
        proptx = new javax.swing.JTextField();
        marcabut = new javax.swing.JButton();
        Colorbut = new javax.swing.JButton();
        matriculabut = new javax.swing.JButton();
        propietariobut = new javax.swing.JButton();
        itvbut = new javax.swing.JButton();
        Añobuttt = new javax.swing.JButton();
        kilometrajebut = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("   Vehiculos");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 47, 168, 83));

        matricula.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        matricula.setForeground(new java.awt.Color(255, 255, 255));
        matricula.setText("Matricula:");
        jPanel1.add(matricula, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 180, -1, -1));
        jPanel1.add(matriculatx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 180, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Propietario:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        volverbut2.setBackground(new java.awt.Color(255, 255, 153));
        volverbut2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        volverbut2.setText("Volver");
        volverbut2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        volverbut2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverbut2ActionPerformed(evt);
            }
        });
        jPanel1.add(volverbut2, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 701, 120, 50));

        mtfield.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mtfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mtfield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mtfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mtfieldActionPerformed(evt);
            }
        });
        jPanel1.add(mtfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 460, 430, 220));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(204, 255, 204));
        jLabel3.setText("Vehiculo:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 60, -1, -1));

        limpiarbut.setBackground(new java.awt.Color(255, 207, 139));
        limpiarbut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        limpiarbut.setText("Limpiar");
        limpiarbut.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        limpiarbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarbutActionPerformed(evt);
            }
        });
        jPanel1.add(limpiarbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 320, 120, 40));

        serviciobox.setBackground(new java.awt.Color(204, 255, 255));
        serviciobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Revisión general", "Chapa", "Pintura", "Reparación piezas", "Ruedas" }));
        serviciobox.setToolTipText("Servicio");
        serviciobox.setBorder(null);
        serviciobox.setName("Servicios"); // NOI18N
        serviciobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                servicioboxActionPerformed(evt);
            }
        });
        jPanel1.add(serviciobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 670, 180, 40));

        textofieldoM.setEditable(false);
        textofieldoM.setBackground(new java.awt.Color(204, 255, 204));
        textofieldoM.setColumns(20);
        textofieldoM.setFont(new java.awt.Font("Calibri", 3, 22)); // NOI18N
        textofieldoM.setRows(5);
        textofieldoM.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        textofieldoM.setMargin(new java.awt.Insets(6, 12, 6, 12));
        jScrollPane3.setViewportView(textofieldoM);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 90, 430, 320));

        buscarbut1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buscarbut1.setText("Buscar");
        buscarbut1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        buscarbut1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarbut1ActionPerformed(evt);
            }
        });
        jPanel1.add(buscarbut1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 320, 120, 40));

        modelobut.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        modelobut.setText("Modelo");
        modelobut.setDefaultCapable(false);
        modelobut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelobutActionPerformed(evt);
            }
        });
        jPanel1.add(modelobut, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 510, 140, 40));
        jPanel1.add(proptx, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 180, -1));

        marcabut.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        marcabut.setText("Marca");
        marcabut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                marcabutActionPerformed(evt);
            }
        });
        jPanel1.add(marcabut, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 460, 140, 40));

        Colorbut.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        Colorbut.setText("Color");
        Colorbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ColorbutActionPerformed(evt);
            }
        });
        jPanel1.add(Colorbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 510, 160, 40));

        matriculabut.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        matriculabut.setText("Matricula");
        matriculabut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculabutActionPerformed(evt);
            }
        });
        jPanel1.add(matriculabut, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 560, 160, 40));

        propietariobut.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        propietariobut.setText("Propietario");
        propietariobut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propietariobutActionPerformed(evt);
            }
        });
        jPanel1.add(propietariobut, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 610, 160, 40));

        itvbut.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        itvbut.setText("Caducidad itv");
        itvbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itvbutActionPerformed(evt);
            }
        });
        jPanel1.add(itvbut, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 460, 160, 40));

        Añobuttt.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        Añobuttt.setText("Año");
        Añobuttt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AñobutttActionPerformed(evt);
            }
        });
        jPanel1.add(Añobuttt, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 140, 40));

        kilometrajebut.setFont(new java.awt.Font("Sitka Display", 1, 18)); // NOI18N
        kilometrajebut.setText("Kilometraje");
        kilometrajebut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kilometrajebutActionPerformed(evt);
            }
        });
        jPanel1.add(kilometrajebut, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 610, 140, 40));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel4.setText("¿Qué desea modificar?");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 400, -1, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Escribe la modificación:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 420, -1, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1046, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 776, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void volverbut2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverbut2ActionPerformed
        // TODO add your handling code here:
        Vehiculos v = new Vehiculos();
        dispose();
        v.setVisible(true);
        v.setLocationRelativeTo(null);
    }//GEN-LAST:event_volverbut2ActionPerformed

    private void modificarTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modificarTextFieldActionPerformed

    private void ServicioRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ServicioRadioButtonActionPerformed
        
    }//GEN-LAST:event_ServicioRadioButtonActionPerformed

    private void itvjRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itvjRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_itvjRadioButton2ActionPerformed

    private void modelojRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelojRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelojRadioButton3ActionPerformed

    private void añojRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_añojRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_añojRadioButton4ActionPerformed

    private void matriculajRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculajRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculajRadioButton5ActionPerformed

    private void propjRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propjRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_propjRadioButton6ActionPerformed

    private void colorjRadioButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_colorjRadioButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_colorjRadioButton7ActionPerformed

    private void kmjRadioButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kmjRadioButton8ActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_kmjRadioButton8ActionPerformed

    private void marcaRadioButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcaRadioButton9ActionPerformed
        // TODO add your handling code here:
 
    }//GEN-LAST:event_marcaRadioButton9ActionPerformed

    
    private void limpiarbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarbutActionPerformed
        // TODO add your handling code here:
        matriculatx.setText("");
        proptx.setText("");
    }//GEN-LAST:event_limpiarbutActionPerformed

    private void servicioboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_servicioboxActionPerformed
if (vehiculo != null) {
        // Obtener el nuevo servicio seleccionado del JComboBox como un String
        String nuevoServicio = (String) serviciobox.getSelectedItem();
        
        // Verificar si se seleccionó una opción válida
        if (nuevoServicio != null) {
            // Actualizar el servicio del vehículo en la base de datos
            vehiculoDAO.actualizarCampoVehiculoServicio(vehiculo, nuevoServicio);
            
            // Mostrar un mensaje de éxito
            JOptionPane.showMessageDialog(null, "Servicio del vehículo actualizado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Mostrar un mensaje de error si no se seleccionó ninguna opción válida
            JOptionPane.showMessageDialog(null, "Debe seleccionar una opción válida.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        // Mostrar un mensaje de error si no hay vehículo seleccionado
        JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún vehículo.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_servicioboxActionPerformed

    private void marcaRadioButton9ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_marcaRadioButton9ItemStateChanged
        
    }//GEN-LAST:event_marcaRadioButton9ItemStateChanged

    private void mtfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mtfieldActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_mtfieldActionPerformed

    private void buscarbut1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarbut1ActionPerformed
        // TODO add your handling code here:
         String matricula = matriculatx.getText();
         String propietario = proptx.getText();
         
    // Llamar al método buscarVehiculo del VehiculoDAO
    VehiculoDAO vehiculoDAO = new VehiculoDAO();
    List<Vehiculo> vehiculosEncontrados = vehiculoDAO.buscarVehiculo(matricula, propietario);

    // Mostrar el primer vehículo encontrado en el TextField txtResultado
    if (!vehiculosEncontrados.isEmpty()) {
        vehiculo = vehiculosEncontrados.get(0);
        System.out.println(vehiculo);
    
       String infoVehiculo = "Marca: " + vehiculo.getMarcaV() + "\n"  +
                      "Modelo: " + vehiculo.getModeloV() + "\n"  +
                      "Año: " + vehiculo.getAñoV() + "\n" +
                      "Kilometraje: " + vehiculo.getKilometrajeV() + " km"+ "\n" +
                      "Fecha caducidad ITV: " + vehiculo.getItvV() + "\n"  +
                      "Color: " + vehiculo.getColorV() + "\n" +
                      "Matrícula: " + vehiculo.getMatriculaV() + "\n"+
                      "Propietario: " + vehiculo.getPropietarioV() + "\n"+
                      "Servicio: " + vehiculo.getServicioV();

                // Ajustar el tamaño del TextField
                FontMetrics metrics = textofieldoM.getFontMetrics(textofieldoM.getFont());
                int width = metrics.stringWidth(infoVehiculo);
                int height = metrics.getHeight();
                textofieldoM.setPreferredSize(new Dimension(width, height));

        textofieldoM.setText(infoVehiculo);
    } else {
        textofieldoM.setText("Vehículo no encontrado.");
        System.out.println("Vehiculo empty");
    }

    // Limpiar los campos después de la búsqueda (opcional)
    matriculatx.setText("");
    proptx.setText("");

    }//GEN-LAST:event_buscarbut1ActionPerformed
    
    private void anoButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoButActionPerformed
        // TODO add your handling code here:
     
    }//GEN-LAST:event_anoButActionPerformed

    private void marcabutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_marcabutActionPerformed
        if (vehiculo != null) {
            // Obtener el valor actualizado del campo de texto mtfield
            String nuevoMarca = mtfield.getText();

            // Actualizar solo el campo de marca en la base de datos
            vehiculoDAO.actualizarCampoVehiculoMarca(vehiculo,nuevoMarca);

            // Mostrar un mensaje de éxito
            JOptionPane.showMessageDialog(null, "Marca del vehículo modificada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Mostrar un mensaje de error si no hay vehículo seleccionado
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún vehículo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_marcabutActionPerformed

    private void modelobutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelobutActionPerformed
        // TODO add your handling code here:
        if (vehiculo != null) {
            // Obtener el valor actualizado del campo de texto mtfield
            String nuevoModelo = mtfield.getText();

            // Actualizar solo el campo de marca en la base de datos
            vehiculoDAO.actualizarCampoVehiculoModelo(vehiculo,nuevoModelo);

            // Mostrar un mensaje de éxito
            JOptionPane.showMessageDialog(null, "Modelo del vehículo modificada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Mostrar un mensaje de error si no hay vehículo seleccionado
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún vehículo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_modelobutActionPerformed

    private void ColorbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ColorbutActionPerformed
        // TODO add your handling code here:
         if (vehiculo != null) {
            // Obtener el valor actualizado del campo de texto mtfield
            String nuevoColor = mtfield.getText();

            // Actualizar solo el campo de marca en la base de datos
            vehiculoDAO.actualizarCampoVehiculoColor(vehiculo,nuevoColor);

            // Mostrar un mensaje de éxito
            JOptionPane.showMessageDialog(null, "Color del vehículo modificada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Mostrar un mensaje de error si no hay vehículo seleccionado
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún vehículo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ColorbutActionPerformed

    private void matriculabutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculabutActionPerformed
        // TODO add your handling code here:
        if (vehiculo != null) {
            // Obtener el valor actualizado del campo de texto mtfield
            String nuevaMatricula = mtfield.getText();

            // Actualizar solo el campo de marca en la base de datos
            vehiculoDAO.actualizarCampoVehiculoMatricula(vehiculo,nuevaMatricula);

            // Mostrar un mensaje de éxito
            JOptionPane.showMessageDialog(null, "Matricula del vehículo modificada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Mostrar un mensaje de error si no hay vehículo seleccionado
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún vehículo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_matriculabutActionPerformed

    private void itvbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itvbutActionPerformed
        // TODO add your handling code here:
        if (vehiculo != null) {
            // Obtener el valor actualizado del campo de texto mtfield
            String nuevaitv = mtfield.getText();

            // Actualizar solo el campo de marca en la base de datos
            vehiculoDAO.actualizarCampoVehiculoItv(vehiculo,nuevaitv);

            // Mostrar un mensaje de éxito
            JOptionPane.showMessageDialog(null, "Caducidad de la itv del vehículo modificada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Mostrar un mensaje de error si no hay vehículo seleccionado
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún vehículo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_itvbutActionPerformed

    private void propietariobutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propietariobutActionPerformed
        // TODO add your handling code here:
        if (vehiculo != null) {
            // Obtener el valor actualizado del campo de texto mtfield
            String nuevoprop = mtfield.getText();

            // Actualizar solo el campo de marca en la base de datos
            vehiculoDAO.actualizarCampoVehiculoPropietario(vehiculo,nuevoprop);

            // Mostrar un mensaje de éxito
            JOptionPane.showMessageDialog(null, "Propietario del vehículo modificada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Mostrar un mensaje de error si no hay vehículo seleccionado
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún vehículo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_propietariobutActionPerformed

    private void AñobutttActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AñobutttActionPerformed
        // TODO add your handling code here:
         if (vehiculo != null) {
            // Obtener el valor actualizado del campo de texto mtfield
            String nuevoaño = mtfield.getText();
          //  int nuevoaño = Integer.parseInt(nuevoa);
            // Actualizar solo el campo de marca en la base de datos
            vehiculoDAO.actualizarCampoVehiculoAño(vehiculo,nuevoaño);

            // Mostrar un mensaje de éxito
            JOptionPane.showMessageDialog(null, "Año del vehículo modificada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Mostrar un mensaje de error si no hay vehículo seleccionado
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún vehículo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_AñobutttActionPerformed

    private void kilometrajebutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kilometrajebutActionPerformed
        // TODO add your handling code here:
        if (vehiculo != null) {
            // Obtener el valor actualizado del campo de texto mtfield
            String nuevokm = mtfield.getText();
            int nuevoValor = Integer.parseInt(nuevokm);
          //  int nuevoaño = Integer.parseInt(nuevoa);
            // Actualizar solo el campo de marca en la base de datos
            vehiculoDAO.actualizarCampoVehiculoKilometraje(vehiculo,nuevoValor);

            // Mostrar un mensaje de éxito
            JOptionPane.showMessageDialog(null, "Kilometraje del vehículo modificada correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Mostrar un mensaje de error si no hay vehículo seleccionado
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún vehículo.", "Error", JOptionPane.ERROR_MESSAGE);
        }
            
    }//GEN-LAST:event_kilometrajebutActionPerformed
    
    /**
     * @param args the command line arguments
     */
 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        
                
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarV().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Añobuttt;
    private javax.swing.JButton Colorbut;
    private javax.swing.JButton buscarbut1;
    private javax.swing.JButton itvbut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JButton kilometrajebut;
    private javax.swing.JButton limpiarbut;
    private javax.swing.JButton marcabut;
    private javax.swing.JLabel matricula;
    private javax.swing.JButton matriculabut;
    private javax.swing.JTextField matriculatx;
    private javax.swing.JButton modelobut;
    private javax.swing.JTextField mtfield;
    private javax.swing.JButton propietariobut;
    private javax.swing.JTextField proptx;
    public javax.swing.JComboBox<String> serviciobox;
    private javax.swing.JTextArea textofieldoM;
    private javax.swing.JButton volverbut2;
    // End of variables declaration//GEN-END:variables
}
