/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.tfg;

import java.awt.Dimension;
import java.awt.FontMetrics;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Álvaro
 */
public class ModificarC extends javax.swing.JFrame {
    private Cliente cliente;
    private final ClientesDAO clientesDAO;
    /**
     * Creates new form ModificarC
     */
    public ModificarC() {
        initComponents();
        clientesDAO = new ClientesDAO();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        dnitextMod = new javax.swing.JTextField();
        buscarbut = new javax.swing.JButton();
        limpiarbut = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        textoAreo = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        volverbut = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        mttfield = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        telefonobut = new javax.swing.JButton();
        direccionbut = new javax.swing.JButton();
        correobut = new javax.swing.JButton();
        spinnerMod = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        propBut = new javax.swing.JButton();
        combodir = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(102, 102, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setPreferredSize(new java.awt.Dimension(1109, 779));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 26)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("       Clientes");
        jLabel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Modificar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 3, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("DNI / NIE:");

        dnitextMod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dnitextModActionPerformed(evt);
            }
        });

        buscarbut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        buscarbut.setText("Buscar");
        buscarbut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        buscarbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarbutActionPerformed(evt);
            }
        });

        limpiarbut.setBackground(new java.awt.Color(255, 207, 139));
        limpiarbut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        limpiarbut.setText("Limpiar");
        limpiarbut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        limpiarbut.setPreferredSize(new java.awt.Dimension(57, 31));
        limpiarbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarbutActionPerformed(evt);
            }
        });

        textoAreo.setEditable(false);
        textoAreo.setBackground(new java.awt.Color(204, 204, 255));
        textoAreo.setColumns(20);
        textoAreo.setFont(new java.awt.Font("Calibri", 3, 22)); // NOI18N
        textoAreo.setRows(5);
        textoAreo.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setViewportView(textoAreo);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 3, 20)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cliente :");

        volverbut.setBackground(new java.awt.Color(255, 255, 153));
        volverbut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        volverbut.setText("Volver");
        volverbut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        volverbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverbutActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel4.setText("¿Qué desea modificar?");

        mttfield.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        mttfield.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mttfield.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        mttfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mttfieldActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 3, 22)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Escribe la modificación:");

        telefonobut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        telefonobut.setText("Teléfono");
        telefonobut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonobutActionPerformed(evt);
            }
        });

        direccionbut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        direccionbut.setText("Dirección");
        direccionbut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                direccionbutActionPerformed(evt);
            }
        });

        correobut.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        correobut.setText("Correo electrónico");
        correobut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                correobutActionPerformed(evt);
            }
        });

        spinnerMod.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Coches en propiedad:");

        propBut.setBackground(new java.awt.Color(102, 255, 102));
        propBut.setForeground(new java.awt.Color(102, 255, 102));
        propBut.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));
        propBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                propButActionPerformed(evt);
            }
        });

        combodir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "Avenida", "Bulevar", "Calle", "Esquina", "Vía", "Camino" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(buscarbut, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(limpiarbut, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addGap(0, 0, Short.MAX_VALUE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(combodir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(direccionbut, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(telefonobut, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(correobut))
                                    .addGap(108, 108, 108))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addGap(12, 12, 12)
                                            .addComponent(spinnerMod, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(propBut, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(0, 0, Short.MAX_VALUE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(dnitextMod, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(mttfield, javax.swing.GroupLayout.PREFERRED_SIZE, 472, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(105, 105, 105))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(volverbut, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(dnitextMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buscarbut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(limpiarbut, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 313, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel3)
                        .addGap(7, 7, 7)
                        .addComponent(mttfield, javax.swing.GroupLayout.PREFERRED_SIZE, 197, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(volverbut, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(telefonobut)
                        .addGap(18, 18, 18)
                        .addComponent(correobut)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(direccionbut)
                                .addGap(26, 26, 26)
                                .addComponent(propBut, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(combodir)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel7)
                                    .addComponent(spinnerMod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(69, 69, 69))))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1060, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mttfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mttfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mttfieldActionPerformed

    private void volverbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverbutActionPerformed
        // TODO add your handling code here:
        Clientes c = new Clientes();
        dispose();
        c.setVisible(true);
        c.setLocationRelativeTo(null);
    }//GEN-LAST:event_volverbutActionPerformed

    private void limpiarbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarbutActionPerformed
        // TODO add your handling code here:
        dnitextMod.setText("");
    }//GEN-LAST:event_limpiarbutActionPerformed

    private void buscarbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarbutActionPerformed
        // TODO add your handling code here:
        String dni = dnitextMod.getText();
        ClientesDAO clientesDAO = new ClientesDAO();
        List<Cliente> clientesEncontrados = clientesDAO.buscarCliente(dni);

        if (!clientesEncontrados.isEmpty()) {
           cliente = clientesEncontrados.get(0);
            System.out.println(cliente);

            String infoCliente = "Nombre: " + cliente.getNombreC()+ "\n"  +
            "Primer apellido: " + cliente.getApellido1C()+ "\n"  +
            "Segundo apellido: " + cliente.getApellido2C()+ "\n" +
            "Teléfono: " + cliente.getTelefonoC()+ "\n" +
            "DNI / NIF: " + cliente.getDniC()+ "\n"  +
            "Dirección: " + cliente.getDireccionC()+ "\n" +
            "Correo electrónico: " + cliente.getCorreoC()+ "\n"+
            "Coches en propiedad: " + cliente.getCochesPropC()+ "\n"+
            "¿Cómo nos conociste?: " + cliente.getConocisteC();

            // Ajustar el tamaño del TextField
            FontMetrics metrics = textoAreo.getFontMetrics(textoAreo.getFont());
            int width = metrics.stringWidth(infoCliente);
            int height = metrics.getHeight();
            textoAreo.setPreferredSize(new Dimension(width, height));

            textoAreo.setText(infoCliente);
        } else {
            textoAreo.setText("Cliente no encontrado.");
        }
    }//GEN-LAST:event_buscarbutActionPerformed

    private void dnitextModActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dnitextModActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_dnitextModActionPerformed

    private void telefonobutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonobutActionPerformed
        // TODO add your handling code here:
        if (cliente != null) {
            // Obtener el valor actualizado del campo de texto mtfield
            String nuevotelefono = mttfield.getText();
            int nuevoValor = Integer.parseInt(nuevotelefono);

            // Actualizar solo el campo de marca en la base de datos
            clientesDAO.actualizarCampoClienteTelefono(cliente,nuevoValor);

            // Mostrar un mensaje de éxito
            JOptionPane.showMessageDialog(null, "Teléfono del cliente modificado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Mostrar un mensaje de error si no hay vehículo seleccionado
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún cliente.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        mttfield.setText("");

    }//GEN-LAST:event_telefonobutActionPerformed

    private void direccionbutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_direccionbutActionPerformed
        // TODO add your handling code here:
        if (cliente != null) {
            // Obtener el valor actualizado del campo de texto mtfield
            String nuevadir = mttfield.getText();
            String tipoDir = combodir.getSelectedItem().toString();
            String nuevardire = (tipoDir + " " + nuevadir);
            // Actualizar solo el campo de marca en la base de datos
            clientesDAO.actualizarCampoClienteDir(cliente,nuevardire);

            // Mostrar un mensaje de éxito
            JOptionPane.showMessageDialog(null, "Dirección del cliente modificado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Mostrar un mensaje de error si no hay vehículo seleccionado
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún cliente.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        mttfield.setText("");
    }//GEN-LAST:event_direccionbutActionPerformed

    private void correobutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_correobutActionPerformed
        // TODO add your handling code here:
          if (cliente != null) {
            // Obtener el valor actualizado del campo de texto mtfield
            String nuevoCorreo = mttfield.getText();

            // Actualizar solo el campo de marca en la base de datos
            clientesDAO.actualizarCampoClienteCorreo(cliente,nuevoCorreo);

            // Mostrar un mensaje de éxito
            JOptionPane.showMessageDialog(null, "Correo electrónico del cliente modificado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Mostrar un mensaje de error si no hay vehículo seleccionado
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún cliente.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        mttfield.setText("");
    }//GEN-LAST:event_correobutActionPerformed

    private void propButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_propButActionPerformed
        // TODO add your handling code here:
        if (cliente != null) {
            // Obtener el valor actualizado del campo de texto mtfield
                    int nuevosprop = (Integer) spinnerMod.getValue();

            // Actualizar solo el campo de marca en la base de datos
            clientesDAO.actualizarCampoClienteProp(cliente,nuevosprop);

            // Mostrar un mensaje de éxito
            JOptionPane.showMessageDialog(null, "Coches en propiedad del cliente modificado correctamente.", "Éxito", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Mostrar un mensaje de error si no hay vehículo seleccionado
            JOptionPane.showMessageDialog(null, "No se ha seleccionado ningún cliente.", "Error", JOptionPane.ERROR_MESSAGE);
        }
        mttfield.setText("");
    }//GEN-LAST:event_propButActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModificarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModificarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModificarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModificarC.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModificarC().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarbut;
    private javax.swing.JComboBox<String> combodir;
    private javax.swing.JButton correobut;
    private javax.swing.JButton direccionbut;
    private javax.swing.JTextField dnitextMod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton limpiarbut;
    private javax.swing.JTextField mttfield;
    private javax.swing.JButton propBut;
    private javax.swing.JSpinner spinnerMod;
    private javax.swing.JButton telefonobut;
    private javax.swing.JTextArea textoAreo;
    private javax.swing.JButton volverbut;
    // End of variables declaration//GEN-END:variables
}
